// Captures a PortalSession by loading an entitylist page in a real browser and
// lifting the session triple off the grid's own entity-grid-data.json POST.
//
// A plain GET of the page sets cookies but no anti-forgery token and no secure
// config; the config is generated by Power Apps JS at render time. So we let the
// list render, intercept the POST it fires, and read the cookies + token +
// base64SecureConfiguration straight off it. After this one bootstrap, grid.ts
// can paginate the same list with plain fetch (see crawlGrid).

import {
  launchBrowser,
  newPortalContext,
  type PwContext,
  type PwRequest,
} from "./browser.ts";
import type { PortalSession } from "./types.ts";

const GRID_PATH = "/_services/entity-grid-data.json/";

export interface BootstrapOptions {
  /** The entitylist page whose grid POST we capture (e.g. a Search page). */
  listPageUrl: string;
  timeoutMs?: number;
}

// Capture a session using a caller-managed browser context (lets a caller reuse
// the same browser to also render detail pages afterwards).
export async function bootstrapEntityListWith(
  ctx: PwContext,
  opts: BootstrapOptions,
): Promise<PortalSession> {
  const timeoutMs = opts.timeoutMs ?? 60_000;
  const page = await ctx.newPage();
  // Hoisted so finally can clear it. If page.goto rejects before `captured` is
  // awaited (e.g. a navigation timeout when several browsers contend for the CI
  // runner), an uncleared timer would later reject an unawaited promise - an
  // unhandledRejection that crashes the whole run instead of being caught by the
  // per-source try/catch in fetch.ts. Clearing it in finally prevents that.
  let timer: ReturnType<typeof setTimeout> | undefined;
  try {
    const captured = new Promise<{ token: string; secureConfig: string; cookieFromReq: string | null; gridUrl: string }>(
      (resolve, reject) => {
        timer = setTimeout(
          () => reject(new Error(`timed out waiting for entity-grid-data.json POST on ${opts.listPageUrl}`)),
          timeoutMs,
        );
        page.on("request", (req: PwRequest) => {
          if (req.method() !== "POST") return;
          if (!req.url().includes(GRID_PATH)) return;
          const headers = req.headers();
          const token = headers["__requestverificationtoken"];
          const postData = req.postData();
          if (!token || !postData) return;
          let secureConfig: string;
          try {
            secureConfig = (JSON.parse(postData) as { base64SecureConfiguration?: string })
              .base64SecureConfiguration ?? "";
          } catch {
            return;
          }
          if (!secureConfig) return;
          clearTimeout(timer);
          resolve({ token, secureConfig, cookieFromReq: headers["cookie"] ?? null, gridUrl: req.url() });
        });
      },
    );

    await page.goto(opts.listPageUrl, { waitUntil: "networkidle", timeout: timeoutMs });
    const { token, secureConfig, cookieFromReq, gridUrl } = await captured;

    const cookieHeader =
      cookieFromReq ??
      (await ctx.cookies()).map((c) => `${c.name}=${c.value}`).join("; ");

    return {
      cookieHeader,
      requestVerificationToken: token,
      base64SecureConfiguration: secureConfig,
      gridUrl,
    };
  } finally {
    if (timer) clearTimeout(timer);
    await page.close();
  }
}

// Convenience wrapper that owns the browser lifecycle for callers that only need
// the list (e.g. they then crawl with plain fetch and never touch the browser
// again).
export async function bootstrapEntityList(opts: BootstrapOptions): Promise<PortalSession> {
  const browser = await launchBrowser();
  try {
    const ctx = await newPortalContext(browser);
    return await bootstrapEntityListWith(ctx, opts);
  } finally {
    await browser.close();
  }
}
